### ISSUE TITLE
How to run the code on custom animated point cloud data?

### ISSUE THREAD

**Issue by aartykov** [stevenlsw/reart#4]
Hello. Thanks for the cool work. How can I run your method on my custom animated point cloud? Should I do any extra coordinate system transfromations?

Thanks!

**Comment by stevenlsw** [comment]
Hi, 

Thanks for your interest in our work. Our work doesn't need extra transformation. The global alignment is optional (i.e. align the point clouds in same coordinate system). You could refer to [Real-world experiment](https://github.com/stevenlsw/reart?tab=readme-ov-file#real-world-experiment) for custom data setting, even the input is not aligned, our method could recover the articulation.
